### ISSUE TITLE
Extended Objects

### ISSUE THREAD

**Issue by bradennapier** [u-minor/atom-yamljson#3]
This does not appear to support embedded objects properly?

```yaml
volume:
        up:
          <<: *param::ramp
          path: VolumeUp
```

will add an actual "<<": key to the json rather than embedding the object directly.
